# Generated by Django 3.0.5 on 2020-04-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='stoner_unknown', max_length=50),
        ),
    ]
