# Generated by Django 3.0.5 on 2020-04-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200418_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
