# Generated by Django 3.0.5 on 2020-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
