# Generated by Django 3.0.5 on 2020-04-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200418_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('thc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True)),
            ],
            options={
                'verbose_name': 'Edible',
                'verbose_name_plural': 'Edibles',
            },
        ),
        migrations.AddField(
            model_name='flower',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='kind',
            field=models.CharField(choices=[('H', 'Hybrid'), ('I', 'Indica'), ('S', 'Sativa')], default='H', max_length=1),
        ),
        migrations.CreateModel(
            name='PreRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Flower')),
            ],
            options={
                'verbose_name': 'Pre-Rolls',
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Flower')),
            ],
            options={
                'verbose_name': 'Cartridges',
            },
        ),
    ]
