# Generated by Django 3.0.5 on 2020-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200418_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'Cartridge', 'verbose_name_plural': 'Cartridges'},
        ),
        migrations.AlterField(
            model_name='flower',
            name='thc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
