# Generated by Django 3.0.5 on 2020-04-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200418_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edible',
            name='thc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
