# Generated by Django 3.0.5 on 2020-04-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200418_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preroll',
            options={'verbose_name': 'Pre-Roll', 'verbose_name_plural': 'Pre-Rolls'},
        ),
        migrations.AlterField(
            model_name='flower',
            name='quantity',
            field=models.DecimalField(blank=True, choices=[(1.0, '1 gram'), (3.5, 'Eighth'), (7.0, 'Quarter'), (14.0, 'Half'), (28.0, 'Ounce')], decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
