# Generated by Django 3.0.5 on 2020-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200418_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='preroll',
            name='quantity',
            field=models.DecimalField(choices=[(1.0, '1 gram'), (3.5, 'Eighth'), (7.0, 'Quarter'), (14.0, 'Half'), (28.0, 'Ounce')], decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
